[package]
publish = false
edition = "2021"
rust-version = "1.69.0"

name = "design-scaffold"
version = "0.0.2"

authors = ["https://github.com/afsec"]
license = "MIT"


[dependencies]
anyhow = { workspace = true }
