[package]
publish = false
name = "web-server"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
design-scaffold = { path = "../design-scaffold" }
