name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rustfmt:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-${{ matrix.backend }}-cargo-${{ hashFiles('**/Cargo.toml') }}

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt
        override: true
    - run: cargo fmt -- --check
    
  build:
    needs: rustfmt
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-${{ matrix.backend }}-cargo-${{ hashFiles('**/Cargo.toml') }}

    - name: Install dependencies
      run: make depend     
     
    - name: Build project
      run: make release
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: brickpack-2022
        path: ./dist/release/brickpack-2022
        retention-days: 5

          #  deploy:
          #    needs: build
          #    runs-on: ubuntu-latest
          #    steps:
          #      - uses: actions/checkout@v2
          #      - name: "Download Artifact"
          #        uses: actions/download-artifact@v2
          #        with:
          #          name: brickpack-2022
          #          path: .heroku-deploy/bin/

          #      - name: Display structure of downloaded files
          #        run: sudo apt-get install tree -y ; tree

          #      - name: "Deploy to HEROKU"
          #        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
          #        with:
          #          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          #          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
          #          heroku_email: ${{secrets.HEROKU_EMAIL}}
          #          buildpack: "https://github.com/afsec/heroku-binary-buildpack"
          #          appdir: ".heroku-deploy" # <- This will point to the api folder in your project

